[package]
name = "cbori"
version = "0.1.0"
authors = ["Cody Schafer <cody@berkshiregrey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
fmt-extra = "0.2"
